// Data extracted from the original React app
const LIGHT = {
  bg:         "#FAF8FF",
  surface:    "#FFFFFF",
  surfaceAlt: "#F3EFFF",
  primary:    "#5B21B6",
  accent:     "#F97316",
  border:     "#E4DCFF",
  text:       "#1E1033",
  muted:      "#6B7280",
  heroFrom:   "#3B0764",
  heroMid:    "#6D28D9",
  heroTo:     "#9333EA",
  navBg:      "rgba(250,248,255,0.96)",
  shadow:     "0 2px 10px rgba(91,33,182,0.08)",
  shadowHov:  "0 8px 28px rgba(91,33,182,0.18)",
  badge:      "#EDE9FE",
  badgeText:  "#5B21B6",
  aiBg:       "#FFF7ED",
  aiBorder:   "#FED7AA",
  aiHeading:  "#92400E",
  aiSub:      "#78350F",
};

;
const DARK = {
  bg:         "#080814",
  surface:    "#12122A",
  surfaceAlt: "#1A1A38",
  primary:    "#9333EA",
  accent:     "#FB923C",
  border:     "#242448",
  text:       "#EDE9FF",
  muted:      "#7B7B9D",
  heroFrom:   "#0A0118",
  heroMid:    "#1E0A4A",
  heroTo:     "#4C1D95",
  navBg:      "rgba(8,8,20,0.97)",
  shadow:     "0 2px 10px rgba(0,0,0,0.5)",
  shadowHov:  "0 8px 28px rgba(147,51,234,0.28)",
  badge:      "#2E1065",
  badgeText:  "#C4B5FD",
  aiBg:       "#1A0E04",
  aiBorder:   "#7C3009",
  aiHeading:  "#FDBA74",
  aiSub:      "#FCA5A5",
};

;
const ILLNESS = {
  "Sickle Cell Disease": {
    L: { pill:"#FEE2E2", text:"#991B1B", accent:"#EF4444" },
    D: { pill:"#3D1010", text:"#FCA5A5", accent:"#F87171" },
  },
  "Cancer": {
    L: { pill:"#EDE9FE", text:"#5B21B6", accent:"#8B5CF6" },
    D: { pill:"#2E1065", text:"#C4B5FD", accent:"#A78BFA" },
  },
  "HIV/AIDS": {
    L: { pill:"#FCE7F3", text:"#9D174D", accent:"#EC4899" },
    D: { pill:"#50072A", text:"#F9A8D4", accent:"#F472B6" },
  },
  "Diabetes": {
    L: { pill:"#DBEAFE", text:"#1E3A8A", accent:"#3B82F6" },
    D: { pill:"#172554", text:"#93C5FD", accent:"#60A5FA" },
  },
  "Kidney Disease": {
    L: { pill:"#FEF3C7", text:"#78350F", accent:"#F59E0B" },
    D: { pill:"#451A03", text:"#FDE68A", accent:"#FBBF24" },
  },
  "Mental Health": {
    L: { pill:"#D1FAE5", text:"#064E3B", accent:"#10B981" },
    D: { pill:"#052E1C", text:"#6EE7B7", accent:"#34D399" },
  },
};

const ILLNESS_ICONS = {
  "Sickle Cell Disease": "🩸",
  "Cancer":              "🎗️",
  "HIV/AIDS":            "❤️‍🩹",
  "Diabetes":            "💉",
  "Kidney Disease":      "🫘",
  "Mental Health":       "🧠",
};

;

const ALL_ILLNESSES = Object.keys(ILLNESS);
const STATES = [
  "All States","Nationwide","Abia","Adamawa","Akwa Ibom","Anambra","Bauchi","Bayelsa",
  "Benue","Borno","Cross River","Delta","Ebonyi","Edo","Ekiti","Enugu","FCT (Abuja)",
  "Gombe","Imo","Jigawa","Kaduna","Kano","Katsina","Kebbi","Kogi","Kwara","Lagos",
  "Nasarawa","Niger","Ogun","Ondo","Osun","Oyo","Plateau","Rivers","Sokoto",
  "Taraba","Yobe","Zamfara",
];;
const ORGANIZATIONS = [
  {
    id:1, name:"Sickle Cell Foundation Nigeria", shortName:"SCFN",
    illnesses:["Sickle Cell Disease"], states:["Lagos","Nationwide"],
    tagline:"Home to Nigeria's first National Sickle Cell Centre",
    description:"The Sickle Cell Foundation Nigeria provides comprehensive care, genetic counselling, and support to individuals and families affected by sickle cell disease. It operates the first dedicated National Sickle Cell Centre in Africa.",
    services:["Free genetic counselling","Hydroxyurea access support","Patient education & awareness","Newborn screening programs","Psychosocial support groups"],
    contact:{ phone:"+234 1 774 0293", email:"info@sicklecellfoundation.com", website:"https://sicklecellfoundation.com", address:"4A Ilabere Avenue, Ilupeju, Lagos" },
    type:"NGO / Foundation", verified:true, tags:["Free counselling","Testing","Patient support"],
  },
  {
    id:2, name:"Sickle Cell Hope Alive Foundation", shortName:"SCHAF",
    illnesses:["Sickle Cell Disease"], states:["Lagos","Rivers","Nationwide"],
    tagline:"Empowering sickle cell warriors with resources and community",
    description:"Sickle Cell Hope Alive Foundation supports individuals and families living with sickle cell disease through financial aid, community building, treatment awareness, and advocacy for improved care access across Nigeria.",
    services:["Financial aid for treatment costs","Patient support groups","Hydroxyurea awareness campaigns","Community advocacy","Educational scholarships for patients"],
    contact:{ phone:"+234 808 521 7800", email:"info@sicklecellfoundation.ng", website:"https://sicklecellfoundation.ng", address:"Lagos, Nigeria" },
    type:"NGO / Foundation", verified:true, tags:["Financial aid","Scholarships","Advocacy"],
  },
  {
    id:3, name:"Project PINK BLUE", shortName:"PPB",
    illnesses:["Cancer"], states:["FCT (Abuja)","Lagos","Nationwide"],
    tagline:"Fighting breast and cervical cancer through free screening",
    description:"Project PINK BLUE is a leading cancer advocacy NGO in Nigeria focused on breast and cervical cancer. They provide free screenings, patient navigation support, and run some of the country's most impactful public awareness campaigns.",
    services:["Free breast cancer screening","Free cervical cancer screening","Patient navigation & support","Awareness campaigns","Treatment fund assistance"],
    contact:{ phone:"+234 818 888 4805", email:"info@projectpinkblue.org", website:"https://projectpinkblue.org", address:"Abuja, FCT" },
    type:"NGO", verified:true, tags:["Free screening","Cancer support","Navigation"],
  },
  {
    id:4, name:"Nigerian Cancer Society", shortName:"NCS",
    illnesses:["Cancer"], states:["Lagos","Nationwide"],
    tagline:"Cancer education, early detection, and patient support",
    description:"The Nigerian Cancer Society promotes early cancer detection, connects patients to treatment support, and runs nationwide education and advocacy programs to improve cancer care outcomes in Nigeria.",
    services:["Cancer awareness & education","Free screening events","Patient support & navigation","Policy advocacy","Caregiver support programs"],
    contact:{ phone:"+234 803 571 1971", email:"info@nigeriancancersociety.org", website:"https://nigeriancancersociety.org", address:"Lagos, Nigeria" },
    type:"Patient Association", verified:true, tags:["Free screening","Advocacy","Caregiver support"],
  },
  {
    id:5, name:"Society for Family Health", shortName:"SFH",
    illnesses:["HIV/AIDS"], states:["FCT (Abuja)","Lagos","Nationwide"],
    tagline:"HIV prevention, testing, and treatment support across Nigeria",
    description:"Society for Family Health is one of Nigeria's largest public health NGOs, providing HIV/AIDS prevention, free testing, counselling, and treatment adherence support across all 36 states and the FCT.",
    services:["Free HIV testing & counselling","Condom distribution","ART adherence support","Prevention programs","Community health outreach"],
    contact:{ phone:"+234 9 461 4751", email:"sfhnig@sfhnigeria.org", website:"https://sfhnigeria.org", address:"8 Port Harcourt Crescent, Area 11, Garki, Abuja" },
    type:"NGO", verified:true, tags:["Free testing","HIV treatment","Nationwide"],
  },
  {
    id:6, name:"National Agency for Control of AIDS", shortName:"NACA",
    illnesses:["HIV/AIDS"], states:["FCT (Abuja)","Nationwide"],
    tagline:"Nigeria's national HIV/AIDS response and free ART coordinator",
    description:"NACA is the federal body coordinating Nigeria's response to HIV/AIDS. Through government health facilities nationwide, NACA oversees free antiretroviral therapy distribution, testing, and PMTCT programs across all states.",
    services:["Free antiretroviral therapy (ART)","HIV counselling & testing","Prevention of mother-to-child transmission","State-level program coordination","Referral network nationwide"],
    contact:{ phone:"+234 9 461 4751", email:"info@naca.gov.ng", website:"https://naca.gov.ng", address:"21 Blantyre Street, Wuse II, Abuja" },
    type:"Government Agency", verified:true, tags:["Free ART","Government","Nationwide"],
  },
  {
    id:7, name:"Lagos State AIDS Control Agency", shortName:"LSACA",
    illnesses:["HIV/AIDS"], states:["Lagos"],
    tagline:"HIV/AIDS prevention and free treatment for Lagos residents",
    description:"LSACA coordinates all HIV/AIDS prevention, treatment, and care programs within Lagos State. They manage free ART distribution and operate testing centres at multiple locations across Lagos.",
    services:["Free antiretrovirals (ART)","HIV testing & counselling","Prevention programs","Palliative care support","Community health outreach"],
    contact:{ phone:"+234 1 460 5700", email:"lsaca@lagosstate.gov.ng", website:"https://lsaca.gov.ng", address:"Secretariat, Alausa, Ikeja, Lagos" },
    type:"Government Agency", verified:true, tags:["Free ART","Lagos residents","Government"],
  },
  {
    id:8, name:"Diabetes Association of Nigeria", shortName:"DAN",
    illnesses:["Diabetes"], states:["Lagos","FCT (Abuja)","Nationwide"],
    tagline:"Education, screening, and support for Nigerians with diabetes",
    description:"The Diabetes Association of Nigeria is dedicated to improving lives of Nigerians with diabetes through patient education, free screening events, insulin access advocacy, and strong support groups across the country.",
    services:["Free blood glucose screening","Patient education programs","Insulin access support","Diabetes support groups","Annual awareness campaigns"],
    contact:{ phone:"+234 803 300 0985", email:"info@diabetesnigeria.org", website:"https://diabetesnigeria.org", address:"Lagos, Nigeria" },
    type:"Patient Association", verified:true, tags:["Free screening","Insulin support","Support groups"],
  },
  {
    id:9, name:"Lagos State Free Dialysis Programme", shortName:"LSFDP",
    illnesses:["Kidney Disease"], states:["Lagos"],
    tagline:"Free kidney dialysis for qualifying Lagos State residents",
    description:"A Lagos State Government initiative providing free or heavily subsidized hemodialysis to qualifying residents. It targets patients who cannot afford the high recurring cost of regular dialysis sessions.",
    services:["Free hemodialysis sessions","Eligibility screening","Referral to partner dialysis centres","Patient nutritional counselling"],
    contact:{ phone:"+234 1 460 5700", email:"info@health.lagosstate.gov.ng", website:"https://health.lagosstate.gov.ng", address:"Lagos State Ministry of Health, Alausa, Ikeja, Lagos" },
    type:"Government Program", verified:true, tags:["Free dialysis","Lagos residents","Government subsidy"],
  },
  {
    id:10, name:"Kidney Foundation of Nigeria", shortName:"KFN",
    illnesses:["Kidney Disease"], states:["Lagos","FCT (Abuja)","Nationwide"],
    tagline:"Advocacy and support for Nigerians with kidney disease",
    description:"The Kidney Foundation of Nigeria promotes kidney health awareness, advocates for affordable dialysis access, and connects patients to subsidized care and financial assistance programs across Nigeria.",
    services:["Kidney disease awareness","Patient referral network","Dialysis access support","Living donor transplant advocacy","Financial assistance programs"],
    contact:{ phone:"+234 802 300 7697", email:"info@kidneyfoundationnigeria.org", website:"https://kidneyfoundationnigeria.org", address:"Lagos, Nigeria" },
    type:"NGO / Foundation", verified:true, tags:["Financial aid","Referrals","Transplant support"],
  },
  {
    id:11, name:"Mentally Aware Nigeria Initiative", shortName:"MANI",
    illnesses:["Mental Health"], states:["Lagos","Nationwide"],
    tagline:"Connecting Nigerians to mental health care and reducing stigma",
    description:"MANI works to reduce mental health stigma and improve access to care in Nigeria. They provide a mental health resource directory, community peer support, mental health first aid training, and patient referrals.",
    services:["Mental health resource directory","Patient referrals to therapists","Online support community","Mental health first aid training","Awareness campaigns"],
    contact:{ phone:"+234 818 880 6607", email:"hello@mani.ng", website:"https://mani.ng", address:"Lagos, Nigeria" },
    type:"NGO", verified:true, tags:["Referrals","Community support","Awareness"],
  },
  {
    id:12, name:"She Writes Woman", shortName:"SWW",
    illnesses:["Mental Health"], states:["Lagos","Nationwide"],
    tagline:"Nigeria's leading 24/7 mental health crisis helpline",
    description:"She Writes Woman operates a 24-hour crisis helpline for Nigerians experiencing mental health distress. Trained counsellors provide free, confidential support for depression, anxiety, trauma, and crisis situations.",
    services:["24/7 mental health crisis helpline","Confidential counselling","Survivor support groups","Peer-to-peer support","Online mental health resources"],
    contact:{ phone:"0800 800 2000", email:"support@shewrites.woman", website:"https://shewrites.woman", address:"Lagos, Nigeria" },
    type:"NGO / Crisis Support", verified:true, tags:["Crisis line","Free support","24/7"],
  },
  {
    id:13, name:"Federal Neuropsychiatric Hospital, Yaba", shortName:"FNH Yaba",
    illnesses:["Mental Health"], states:["Lagos"],
    tagline:"Nigeria's largest federal mental health institution",
    description:"The Federal Neuropsychiatric Hospital Yaba is Nigeria's oldest and largest federal mental health facility, offering inpatient, outpatient, and community psychiatry services. Subsidized treatment is available for qualifying patients.",
    services:["Inpatient psychiatric care","Outpatient counselling & therapy","Substance use disorder treatment","Subsidized medications","Emergency mental health care"],
    contact:{ phone:"+234 1 801 1600", email:"fnhy@fnhyaba.gov.ng", website:"https://fnhyaba.gov.ng", address:"8 Harvey Road, Yaba, Lagos" },
    type:"Government Hospital", verified:true, tags:["Subsidized care","Inpatient","Outpatient"],
  },
];;
